### ISSUE TITLE
umd

### ISSUE THREAD

**Issue by taoqf** [wwilsman/Datepicker.js#11]
it seems should be 
```js
  if (typeof define === 'function' && define.amd) {
    define('Datepicker', factory);
  } else if (typeof exports === 'object') {
    module.exports = factory;
  } else {
    root.Datepicker = factory;
  }
```
I find there is too many changes between the version in npm and github, and could not help to fix this.

another bug:
it seems should use `relative` instead of `absolute` in css 
```css
.datePicker.has-popup .datePicker__container {
	position: relative;
}
```
